/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiCloseThick: typeof import('~icons/mdi/close-thick')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiInstagram: typeof import('~icons/mdi/instagram')['default']
    IMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
    IMdiLock: typeof import('~icons/mdi/lock')['default']
    IMdiLockOpen: typeof import('~icons/mdi/lock-open')['default']
    IMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IMdiMenu: typeof import('~icons/mdi/menu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
